### ISSUE TITLE
Update Dockerfiles to Ubuntu 18

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#105]
This issue is to update https://github.com/ibpsa/project1-boptest/blob/master/Dockerfile and https://github.com/ibpsa/project1-boptest/blob/master/testing/Dockerfile to Ubuntu 18 instead of 16.

**Comment by dhblum** [comment]
The following message is given when compiling models with the new docker image:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/JModelica/Python/pymodelica/compiler_logging.py", line 218, in run
    xml.sax.parse(self.stream, LogErrorParser(self.result))
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 116, in parse
    self._close_source()
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 235, in _close_source
    file.close()
AttributeError: KeepLastStream instance has no attribute 'close'
```

However, there seems to be no adverse side affects.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/108.
