### ISSUE TITLE
Update reference results for updated JModelica docker

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#130]
This issue is to update reference results as needed for an update in the JModelica docker image.  See https://github.com/lbl-srg/docker-ubuntu-jmodelica/issues/6.

**Comment by dhblum** [comment]
Error Report is as follows.  New results have been verified and are acceptable in all cases.

```
==============
TESTING REPORT
==============

The following test modules were run:
test_testcase2.py
test_forecast.py
test_testcase1.py
test_data.py
test_parser.py
The total number of individual tests run was 50.

-------------
Not all tests passed.  See testing_report.txt for more detailed report.
-------------


From test_testcase2.py
=========================
Of 15 tests run...
Passed: 11
Failures: 4
Errors: 0

Failure Messages
----------------
Failure 1:
Traceback (most recent call last):
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/utilities.py", line 297, in test_advance_no_data
    self.assertAlmostEqual(y[key], self.y_ref[key], places=3)
AssertionError: 2422.6914961978637 != 2420.311404179384 within 3 places

Failure 0:
Traceback (most recent call last):
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/utilities.py", line 315, in test_advance_false_overwrite
    self.assertAlmostEqual(y[key], self.y_ref[key], places=3)
AssertionError: 2422.6914961978637 != 2420.311404179384 within 3 places

Failure 3:
Traceback (most recent call last):
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/test_testcase2.py", line 42, in test_run
    self.assertAlmostEqual(kpi['ener_tot'], kpi_ref['ener_tot'], places=3)
AssertionError: 147.1202022345602 != 147.133983414 within 3 places

Failure 2:
Traceback (most recent call last):
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/test_testcase2.py", line 83, in test_run
    self.assertAlmostEqual(kpi['ener_tot'].get_values()[0], kpi_ref['ener_tot'], places=3)
AssertionError: 147.1202022345602 != 147.133983414 within 3 places


Error Messages
----------------

From test_forecast.py
=========================
Of 2 tests run...
Passed: 2
Failures: 0
Errors: 0

Failure Messages
----------------

Error Messages
----------------

From test_testcase1.py
=========================
Of 15 tests run...
Passed: 13
Failures: 2
Errors: 0

Failure Messages
----------------
Failure 1:
Traceback (most recent call last):
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/test_testcase1.py", line 59, in test_run
    self.compare_ref_timeseries_df(df,ref_filepath)
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/utilities.py", line 101, in compare_ref_timeseries_df
    self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
AssertionError: Max error (10.1025581798) in trajectory greater than tolerance (0.001) at index 395. y_test: 261.10734, y_ref:271.17278 Key is PHea_y.

Failure 0:
Traceback (most recent call last):
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/test_testcase1.py", line 94, in test_run
    self.compare_ref_timeseries_df(df,ref_filepath)
  File "/home/dhbubu/git/ibpsa/project1-boptest/project1-boptest/testing/utilities.py", line 101, in compare_ref_timeseries_df
    self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
AssertionError: Max error (0.00531539727525) in trajectory greater than tolerance (0.001) at index 394. y_test: 19.899142, y_ref:19.894081 Key is TRooAir_y.


Error Messages
----------------

From test_data.py
=========================
Of 10 tests run...
Passed: 10
Failures: 0
Errors: 0

Failure Messages
----------------

Error Messages
----------------

From test_parser.py
=========================
Of 8 tests run...
Passed: 5
Failures: 3
Errors: 0

Failure Messages
----------------
Failure 1:
Traceback (most recent call last):
  File "/usr/local/testing/test_parser.py", line 238, in test_simulate_no_overwrite
    self.compare_ref_timeseries_df(df,ref_filepath)
  File "/usr/local/testing/utilities.py", line 101, in compare_ref_timeseries_df
    self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
AssertionError: Max error (0.00275914305077) in trajectory greater than tolerance (0.001) at index 315. y_test: 300.77213, y_ref:300.77488 Key is TZone_y.

Failure 0:
Traceback (most recent call last):
  File "/usr/local/testing/test_parser.py", line 272, in test_simulate_act_overwrite
    self.compare_ref_timeseries_df(df,ref_filepath)
  File "/usr/local/testing/utilities.py", line 101, in compare_ref_timeseries_df
    self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
AssertionError: Max error (0.00252859547626) in trajectory greater than tolerance (0.001) at index 176. y_test: 293.17999, y_ref:293.17747 Key is TZone_y.

Failure 2:
Traceback (most recent call last):
  File "/usr/local/testing/test_parser.py", line 255, in test_simulate_set_overwrite
    self.compare_ref_timeseries_df(df,ref_filepath)
  File "/usr/local/testing/utilities.py", line 101, in compare_ref_timeseries_df
    self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
AssertionError: Max error (0.00222736542959) in trajectory greater than tolerance (0.001) at index 317. y_test: 301.40586, y_ref:301.40808 Key is TZone_y.
```

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/131.
