### ISSUE TITLE
Error when running examples/python/twoday_p.py

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#168]
Output is:
```
$ python examples/python/twoday_p.py
Traceback (most recent call last):
  File "examples/python/twoday_p.py", line 165, in <module>
    kpi,res,customizedkpis_result = run(kpiconfig='custom_kpi/custom_kpis.config')
TypeError: run() got an unexpected keyword argument 'kpiconfig'
```
Line 165 of ``examples/python/twoday_p.py`` needs to be checked.  So does ``testing/test_testcase1.py`` customized kpi results.

**Comment by dhblum** [comment]
Once the above error is fixed, another error is:
```
Traceback (most recent call last):
  File "twoday_p.py", line 165, in <module>
    kpi,res,customizedkpis_result = run(customized_kpi_config='custom_kpi/custom_kpis_example.config')
  File "twoday_p.py", line 133, in run
    print('{0}: {1} {2}'.format(key, kpi[key], unit))
UnboundLocalError: local variable 'unit' referenced before assignment
```

This indicates that the wrapped.fmu is not updated from addition of the CO2Concentration.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/171.
