### ISSUE TITLE
Update to latest IBPSA master

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#196]
Unit tests are failing with the most recent merge to the IBPSA master: https://github.com/ibpsa/modelica-ibpsa/issues/1340.  The message is as follows:

```
From test_data.py
=========================
Of 14 tests run...
Passed: 12
Failures: 1
Errors: 1
Failure Messages
----------------
Failure 0:
Traceback (most recent call last):
  File "/usr/local/testing/test_data.py", line 61, in test_generate_weather
    self.compare_ref_timeseries_df(df_gen, ref_filepath)
  File "/usr/local/testing/utilities.py", line 101, in compare_ref_timeseries_df
    self.assertTrue(results['Pass'], '{0} Key is {1}.'.format(results['Message'],key))
AssertionError: Max error (0.00940195134318) in trajectory greater than tolerance (0.001) at index 27. y_test: 0.010521042, y_ref:0.01061984 Key is HDirNor.
Error Messages
----------------
Error 0:
Traceback (most recent call last):
  File "/usr/local/testing/test_data.py", line 221, in test_save_data_and_kpisjson
    self.man.save_data_and_kpisjson(fmu_path=self.case.fmupath)
  File "/usr/local/testing/data/data_manager.py", line 223, in save_data_and_kpisjson
    self._append_csv_data()
  File "/usr/local/testing/data/data_manager.py", line 170, in _append_csv_data
    'key, it is in the format: variable[zone_identifier] '.format(col,f))
KeyError: 'The data column ceiHei from file /usr/local/testing/testcase2/models/Resources/weather.csv does not match any of the allowed column keys and therefore it cannot be saved within the compiled fmu. Test case data variables are used for forecasting and KPI calculation. If you want this variable to be part of the test case data make sure that the column has a key with any of the specified formats in categories.json and that, if it is a zone related key, it is in the format: variable[zone_identifier] '
```

In particular,  the weather bus output ``celHei`` was changed to ``ceiHei``, requiring the same change to ``data/categories.json``.

**Comment by dhblum** [comment]
Updates merged in https://github.com/ibpsa/project1-boptest/issues/196.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/189 via https://github.com/ibpsa/project1-boptest/issues/188.
