### ISSUE TITLE
Unit tests failing due to matplotlib and numpy dependency

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest#655]
Unit tests are failing with (see https://app.travis-ci.com/github/ibpsa/project1-boptest/jobs/624003987):

```
Traceback (most recent call last):
  File "/home/travis/build/ibpsa/project1-boptest/testing/report.py", line 9, in <module>
    import utilities
  File "/home/travis/build/ibpsa/project1-boptest/testing/utilities.py", line 15, in <module>
    import matplotlib.pyplot as plt
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/PIL/Image.py", line 68, in <module>
    from ._typing import StrOrBytesPath, TypeGuard
  File "/home/travis/virtualenv/python3.9.6/lib/python3.9/site-packages/PIL/_typing.py", line 10, in <module>
    NumpyArray = npt.NDArray[Any]
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
makefile:155: recipe for target 'test_parser' failed
make: *** [test_parser] Error 1
```

matplotlib and numpy versions are already specified in travis config file using:
```
install: pip install --upgrade pip && pip install pandas==1.2.5 numpy==1.20.2 matplotlib==3.3.4 requests==2.25.1
```

This issue is to address this.

**Comment by dhblum** [comment]
Closed by https://github.com/ibpsa/project1-boptest/pull/659.
